---
title: "Arc-length parametrization"
date: "Last modified: `r format(Sys.time(), '%d-%m-%Y.')`"
output:
  html_document:
    mathjax: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    highlight: pygments
    theme: flatly
    code_folding: hide # class.source = "fold-hide" to hide code and add a button to show it
    df_print: paged
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    number_sections: true
    fig_caption: true
    code_download: true
    css: visual.css
always_allow_html: true
bibliography: 
  - references.bib
  - grateful-refs.bib
header-includes:
  - \newcommand{\ar}{\mathbb{R}}
  - \newcommand{\llav}[1]{\left\{#1\right\}}
  - \newcommand{\pare}[1]{\left(#1\right)}
  - \newcommand{\Ncal}{\mathcal{N}}
  - \newcommand{\Vcal}{\mathcal{V}}
  - \newcommand{\Ecal}{\mathcal{E}}
  - \newcommand{\Wcal}{\mathcal{W}}
  - \newcommand{\almosteverywhere}{\mathrm{a.e.}\;}
---

Go back to the [Contents](about.html) page.

<div style="color: #2c3e50; text-align: right;">
********  
<strong>Press Show to reveal the code chunks.</strong>  

********
</div>


```{r}
# Create a clipboard button on the rendeblack HTML page
source(here::here("clipboard.R")); clipboard
# Set seed for reproducibility
set.seed(1982) 
# Set global options for all code chunks
knitr::opts_chunk$set(
  # Disable messages printed by R code chunks
  message = FALSE,    
  # Disable warnings printed by R code chunks
  warning = FALSE,    
  # Show R code within code chunks in output
  echo = TRUE,        
  # Include both R code and its results in output
  include = TRUE,     
  # Evaluate R code chunks
  eval = FALSE,       
  # Enable caching of R code chunks for faster rendering
  cache = FALSE,      
  # Align figures in the center of the output
  fig.align = "center",
  # Enable retina display for high-resolution figures
  retina = 2,
  # Show errors in the output instead of stopping rendering
  error = TRUE,
  # Do not collapse code and output into a single block
  collapse = FALSE
)
# Start the figure counter
fig_count <- 0
# Define the captioner function
captioner <- function(caption) {
  fig_count <<- fig_count + 1
  paste0("Figure ", fig_count, ": ", caption)
}

```

```{r, eval = TRUE}
library(MetricGraph)
library(ggplot2)
library(reshape2)
library(dplyr)
library(viridis)
library(plotly)
library(patchwork)
library(slackr)
source("keys.R")
slackr_setup(token = token) # token comes from keys.R
```


```{r}
capture.output(
  knitr::purl(here::here("functionality1.Rmd"), output = here::here("functionality1.R")),
  file = here::here("old/purl_log.txt")
)
source(here::here("functionality1.R"))
```



```{r, eval  = FALSE}
library(plotly)

# Parameters
a <- 1
b <- 0.5

# Total arc-length
L <- sqrt(a^2 + b^2) * 6*pi

# Arc-length parametrization (helix around x-axis)
alpha_tilde <- function(s){
  t <- s / sqrt(a^2 + b^2)
  x <- b*t
  y <- a*cos(t)
  z <- a*sin(t)
  data.frame(x=x, y=y, z=z)
}

max_x <- b * (L / sqrt(a^2 + b^2))

half_max_x <- max_x / 2

# Smooth helix
n_smooth <- 500
s_smooth <- seq(0, L, length.out = n_smooth)
curve_smooth <- alpha_tilde(s_smooth)

# Points for mapping lines
n_map <- 50
s_map <- seq(0, L, length.out = n_map)
curve_map <- alpha_tilde(s_map)

# Interval along x-axis
int_map <- data.frame(
  x = s_map * max_x / L,
  y = rep(0, n_map),
  z = rep(0, n_map)
)

# Build mapping lines
rows <- lapply(1:n_map, function(i) {
  list(int_map[i, ], curve_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result <- do.call(rbind, unlist(rows, recursive = FALSE))

# Plot
p <- plot_ly() |>
  
  # Smooth helix
  add_trace(
    data = curve_smooth,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "#0000C8", width = 7),
    showlegend = FALSE
  ) |>
  
  # Sample helix points
  add_trace(
    data = curve_map,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "markers",
    marker = list(color = "black", size = 4),
    showlegend = FALSE
  ) |>
  
  # Interval [0,L]
  add_trace(
    data = int_map,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "#0000C8", width = 7),
    showlegend = FALSE
  ) |>
  
  # Interval points
  add_trace(
    data = int_map,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "markers",
    marker = list(color = "black", size = 4),
    showlegend = FALSE
  ) |>
  
  # Mapping lines
  add_trace(
    data = result,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "gray", width = 1),
    showlegend = FALSE
  )
 
p1 <- layout(p,
            margin = list(l = 0, r = 0, b = 0, t = 0),
            scene = list(
              xaxis = list(title = "x",  range = c(0, max_x)),
              yaxis = list(title = "y", range = c(-1, 1)),
              zaxis = list(title = "z", range = c(-1, 1)),
              #aspectmode="data",
              aspectratio = list(x = max_x/2, y = 1, z = 1),
              camera = list(eye = list(x = 0, y = -4, z = 4),
                            center = list(x = 0, y = 0, z = 0))
            )
)

save(p1, file = here::here("graphs6p1.Rdata"))
load(here::here("graphs6p1.Rdata"))
p1
```



```{r}
library(plotly)

# Parameters
a <- 1
b <- 0.5
TT <- 6*pi
# Total arc-length
L <- sqrt(a^2 + b^2) * TT

half_L <- L / 2


max_x <- b * (L / sqrt(a^2 + b^2))

half_max_x <- max_x / 2

dist_to_move <- half_L - half_max_x

# Arc-length parametrization (helix around x-axis)
alpha_tilde <- function(s){
  t <- s / sqrt(a^2 + b^2)
  x_shift <- TT*(sqrt(a^2 + b^2) - b) / 2
  x <- b * t + x_shift
  y <- a * cos(t)
  z <- a * sin(t)
  data.frame(x=x, y=y, z=z)
}

a0 = alpha_tilde(0)
aL = alpha_tilde(L)
aLh = alpha_tilde(half_L)

# Smooth helix
n_smooth <- 500
s_smooth <- seq(0, L, length.out = n_smooth)
curve_smooth <- alpha_tilde(s_smooth)

# Points for mapping lines
n_map <- 50
s_map <- seq(0, L, length.out = n_map)
curve_map <- alpha_tilde(s_map)

# Interval along x-axis
int_map <- data.frame(
  x = s_map,
  y = rep(0, n_map),
  z = rep(0, n_map)
)

# Build mapping lines
rows <- lapply(1:n_map, function(i) {
  list(int_map[i, ], curve_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result <- do.call(rbind, unlist(rows, recursive = FALSE))

# Plot
p <- plot_ly() |>
  
  # Smooth helix
  add_trace(
    data = curve_smooth,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "darkgreen", width = 7),
    showlegend = FALSE
  ) |>
  
  # Sample helix points
  add_trace(
    data = curve_map,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "markers",
    marker = list(color = "black", size = 3),
    showlegend = FALSE
  ) |>
  
  # Interval [0,L]
  add_trace(
    data = int_map,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "#0000C8", width = 7),
    showlegend = FALSE
  ) |>
  
  # Interval points
  add_trace(
    data = int_map,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "markers",
    marker = list(color = "black", size = 3),
    showlegend = FALSE
  ) |>
  
  # Mapping lines
  add_trace(
    data = result,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "gray", width = 1),
    showlegend = FALSE
  )
 

p2 <- p |> config(mathjax = 'cdn') |>
            layout(p,
                   font = list(family = "Palatino"),
            margin = list(l = 0, r = 0, b = 0, t = 0),
            scene = list(xaxis = list(title = list(text = "x", font = list(color = colaxnn)),  tickfont = list(color = colaxnn),  range = c(0, L)),
              yaxis = list(title = list(text = "y", font = list(color = colaxnn)),  tickfont = list(color = colaxnn), range = c(-1, 1)),
              zaxis = list(title = list(text = "z", font = list(color = colaxnn)),  tickfont = list(color = colaxnn), range = c(-1, 1)),
              #aspectmode="data",
              aspectratio = list(x = L/3, y = 1, z = 1),
              camera = list(eye = list(x = 0, y = -4, z = 4),
                            center = list(x = 0, y = 0, z = 0)),
              annotations = list(
                list(
               x = 0, y = 0, z = 0,
               text = TeX("0"),
               textangle = 0, ax = 0, ay = 35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = L, y = 0, z = 0,
               text = TeX("\\ell"),
               textangle = 0, ax = 0, ay = 35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),   
                list(
               x = aLh$x, y = aLh$y, z = aLh$z,
               text = TeX("e"),
               textangle = 0, ax = 0, ay = 35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = aL$x, y = aL$y, z = aL$z,
               text = TeX("v_2"),
               textangle = 0, ax = 0, ay = 35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),      
             list(
               x = a0$x, y = a0$y, z = a0$z,
               text = TeX("v_1"),
               textangle = 0, ax = 0, ay = 35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1))
            )
)

save(p2, file = here::here("graphs6p2.Rdata"))
```


```{r, eval =TRUE, fig.height = 7, out.width = "100%"}
load(here::here("graphs6p2.Rdata"))
p2
```



```{r, eval = FALSE}
library(plotly)
n_smooth <- 1000

TT <- 3*pi
# parameter
t <- seq(0, TT, length.out = n_smooth)

# speed
speed <- sqrt(1 + cos(t)^2)

# arc-length function
s <- pracma::cumtrapz(t, speed)
# s <- cumsum(c(0, diff(t) * (head(speed,-1) + tail(speed,-1))/2))

L <- max(s)

half_L <- L / 2
half_TT <- TT / 2
dist_to_move <- abs(half_L - half_TT)

y_shift <- 4
# curve alpha(t)
x <- t + dist_to_move
y <- sin(t) + y_shift
z <- rep(0,length(t))

curve_smooth <- data.frame(x = x, y = y, z = z)


n_map <- 25
# points where we draw connectors
idx <- seq(1, length(t), length.out = n_map)


curve_map <- data.frame(x = x[idx], y = y[idx], z = z[idx])
int_map <- data.frame(x = s[idx], y = rep(0, n_map), z = rep(0, n_map))


# Build mapping lines
rows <- lapply(1:n_map, function(i) {
  list(int_map[i, ], curve_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result <- do.call(rbind, unlist(rows, recursive = FALSE))

s_circ <- L
radius <- s_circ / (2*pi)
x_shift_for_circle <- radius + TT + dist_to_move

theta <- seq(from=-pi,to=pi,length.out = n_smooth)
circle_curve <- data.frame(x = radius*cos(theta) + x_shift_for_circle, 
                    y = radius*sin(theta) + y_shift, 
                    z = rep(0, length(theta)))


circle_map <- circle_curve[idx, ]
dist_to_move_circle <- abs(half_L - y_shift)
int_map_circle <- data.frame(x = rep(x_shift_for_circle +2*radius, n_map), y = s[idx]-dist_to_move_circle, z = rep(0, n_map))

# Build mapping lines for circle
rows <- lapply(1:n_map, function(i) {
  list(int_map_circle[i, ], circle_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result_for_circle <- do.call(rbind, unlist(rows, recursive = FALSE))

p <- plot_ly() |>
  # smooth sin curve
  add_trace(data = curve_smooth,
  x = ~x, y = ~y, z = ~z,
  type = "scatter3d",
  mode = "lines",
  line = list(width = 7, color = "#0000C8"),
    showlegend = FALSE
) |>
  # sin curve
  add_trace(data = curve_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 3, color = "black"),
    showlegend = FALSE
) |>
  # smooth circle curve
  add_trace(data = circle_curve,
  x = ~x, y = ~y, z = ~z,
  type = "scatter3d",
  mode = "lines",
  line = list(width = 7, color = "darkgreen"),
    showlegend = FALSE
) |>  
  add_trace(data = circle_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 3, color = "black"),
    showlegend = FALSE
) |>
  # interval [0,L]
add_trace(data = int_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "lines+markers",
  line = list(width = 7, color = "#0000C8"),
  marker = list(size = 3, color = "black"),
    showlegend = FALSE
) |>
  # interval for circle
  add_trace(data = int_map_circle,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "lines+markers",
  line = list(width = 7, color = "darkgreen"),
  marker = list(size = 3, color = "black"),
    showlegend = FALSE
) |>
  # Mapping lines
  add_trace(
    data = result,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "gray", width = 1),
    showlegend = FALSE
  ) |>
  # Mapping lines for circle
  add_trace(
    data = result_for_circle,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = "gray", width = 1),
    showlegend = FALSE
  )


p <- layout(
  p,
  scene = list(
    xaxis = list(title = "x"),
    yaxis = list(title = "y"),
    zaxis = list(title = ""),
    aspectratio = list(x = x_shift_for_circle +2*radius, y = L, z = L),
              camera = list(eye = list(x = 0, y = -L, z = L),
                            center = list(x = 0, y = 0, z = 0))
  )
)

p
```


# WITH GRADIENT

```{r}
library(plotly)
n_smooth <- 1000

TT <- 3*pi
# parameter
t <- seq(0, TT, length.out = n_smooth)

# speed
speed <- sqrt(1 + cos(t)^2)

# arc-length function
s <- pracma::cumtrapz(t, speed)
# s <- cumsum(c(0, diff(t) * (head(speed,-1) + tail(speed,-1))/2))

L <- max(s)

half_L <- L / 2
half_TT <- TT / 2
dist_to_move <- abs(half_L - half_TT)

y_shift <- 4
# curve alpha(t)
x <- t + dist_to_move
y <- sin(t) + y_shift
z <- rep(0,length(t))

curve_smooth <- data.frame(x = x, y = y, z = z)


n_map <- 25
# points where we draw connectors
idx <- seq(1, length(t), length.out = n_map)


curve_map <- data.frame(x = x[idx], y = y[idx], z = z[idx])
int_map <- data.frame(x = s[idx], y = rep(0, n_map), z = rep(0, n_map))



# Build mapping lines
rows <- lapply(1:n_map, function(i) {
  list(int_map[i, ], curve_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result <- do.call(rbind, unlist(rows, recursive = FALSE))

s_circ <- L
radius <- s_circ / (2*pi)
x_shift_for_circle <- radius + TT + dist_to_move

theta <- seq(from=-pi,to=pi,length.out = n_smooth)
circle_curve <- data.frame(x = radius*cos(theta) + x_shift_for_circle, 
                    y = radius*sin(theta) + y_shift, 
                    z = rep(0, length(theta)))


circle_map <- circle_curve[idx, ]
dist_to_move_circle <- abs(half_L - y_shift)
int_map_circle <- data.frame(x = rep(x_shift_for_circle +2*radius, n_map), y = s[idx]-dist_to_move_circle, z = rep(0, n_map))

# Build mapping lines for circle
rows <- lapply(1:n_map, function(i) {
  list(int_map_circle[i, ], circle_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result_for_circle <- do.call(rbind, unlist(rows, recursive = FALSE))

v1 <- curve_map[1, ]
v2 <- curve_map[n_map, ]
e1 <- curve_map[ceiling(n_map/2), ]
e2 <- circle_map[ceiling(n_map/2), ]
zero1 <- int_map[1, ]
le1 <- int_map[n_map, ]

zero2 <- int_map_circle[1, ]
le2 <- int_map_circle[n_map, ]

vertex <- rbind(v1, v2, zero1, zero2, le1, le2)

p <- plot_ly() |>
  # smooth sin curve
  add_trace(data = curve_smooth,
  x = ~x, y = ~y, z = ~z,
  type = "scatter3d",
  mode = "lines",
  line = list(width = 7, color = "black"),
    showlegend = FALSE
) |>
  # sin curve
  add_trace(data = curve_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  # smooth circle curve
  add_trace(data = circle_curve,
  x = ~x, y = ~y, z = ~z,
  type = "scatter3d",
  mode = "lines",
  line = list(width = 7, color = "black"),
    showlegend = FALSE
) |>  
  add_trace(data = circle_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  # interval [0,L]
add_trace(data = int_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "lines+markers",
  line = list(width = 7, color = "black"),
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  # interval for circle
  add_trace(data = int_map_circle,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "lines+markers",
  line = list(width = 7, color = "black"),
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  add_trace(data = vertex,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 5, color = "black"),
    showlegend = FALSE
) |> add_trace(
    type = "cone",
    x = e1$x,
    y = e1$y,
    z = e1$z,
    u = 1,
    v = 0,
    w = 0,
    sizemode = "absolute",
    sizeref = 0.4,
    colorscale = list(c(0, 1), c("green", "green")),
    showscale = FALSE
  ) |> add_trace(
    type = "cone",
    x = e2$x,
    y = e2$y,
    z = e2$z,
    u = 0,
    v = 1,
    w = 0,
    sizemode = "absolute",
    sizeref = 0.4,
    colorscale = list(c(0, 1), c("green", "green")),
    showscale = FALSE
  )

pal <- colorRampPalette(c("royalblue", "cyan", "yellow", "red"))(n_map)


dx <- int_map$x - curve_map$x
dy <- int_map$y - curve_map$y
dz <- int_map$z - curve_map$z

dxc <- int_map_circle$x - circle_map$x
dyc <- int_map_circle$y - circle_map$y
dzc <- int_map_circle$z - circle_map$z


for(i in 1:n_map){

  seg <- rbind(
    int_map[i, ],
    curve_map[i, ]
  )
  
  seg2 <- rbind(
    int_map_circle[i, ],
    circle_map[i, ]
  )

  p <- p |> add_trace(
    data = seg,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = pal[i], width = 1),
    showlegend = FALSE
  ) |> add_trace(
    data = seg2,
    x = ~x, y = ~y, z = ~z,
    type = "scatter3d",
    mode = "lines",
    line = list(color = pal[i], width = 1),
    showlegend = FALSE
  ) |> add_trace(
    type = "cone",
    x = int_map$x[i],
    y = int_map$y[i],
    z = int_map$z[i],
    u = dx[i],
    v = dy[i],
    w = dz[i],
    sizemode = "absolute",
    sizeref = 0.2,
    anchor = "tip",
    colorscale = list(c(0, pal[i]), c(1, pal[i])),
    showscale = FALSE
  ) |> add_trace(
    type = "cone",
    x = int_map_circle$x[i],
    y = int_map_circle$y[i],
    z = int_map_circle$z[i],
    u = dxc[i],
    v = dyc[i],
    w = dzc[i],
    sizemode = "absolute",
    sizeref = 0.2,
    anchor = "tip",
    colorscale = list(c(0, pal[i]), c(1, pal[i])),
    showscale = FALSE
  )
}



p3 <- p |>
  config(mathjax = 'cdn') |> 
  layout(p,
         font = list(family = "Palatino"),
            margin = list(l = 0, r = 0, b = 0, t = 0),
            scene = list(xaxis = list(title = list(text = "x", font = list(color = colaxnn)),  tickfont = list(color = colaxnn),  range = c(0, x_shift_for_circle +2*radius)*1.01),
              yaxis = list(title = list(text = "y", font = list(color = colaxnn)),  tickfont = list(color = colaxnn), range = range(int_map_circle$y)),
              zaxis = list(title = list(text = "z", font = list(color = colaxnn)),  tickfont = list(color = colaxnn), range = c(-1, 1)),
    aspectratio = list(x = x_shift_for_circle +2*radius, y = L, z = L),
              camera = list(eye = list(x = 0, y = -L*1.5, z = L*1.5),
                            center = list(x = 0, y = 0, z = 0)),
    annotations = list(
      list(
               x = zero1$x, y = zero1$y, z = zero1$z,
               text = TeX("0"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
      list(
               x = zero2$x, y = zero2$y, z = zero2$z,
               text = TeX("0"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
      list(
               x = le1$x, y = le1$y, z = le1$z,
               text = TeX("\\ell_{e_1}"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
      list(
               x = le2$x, y = le2$y, z = le2$z,
               text = TeX("\\ell_{e_2}"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
                list(
               x = v1$x, y = v1$y, z = v1$z,
               text = TeX("v_1"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = v2$x, y = v2$y, z = v2$z,
               text = TeX("v_2"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = e1$x, y = e1$y, z = e1$z,
               text = TeX("e_1"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = e2$x, y = e2$y, z = e2$z,
               text = TeX("e_2"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1))
  )
)

save(p3, file = here::here("graphs6p3.Rdata"))
```


```{r, eval =TRUE, fig.height = 7, out.width = "100%"}
load(here::here("graphs6p3.Rdata"))
p3
```



# WITH GRADIENT SHARED 

```{r}
library(plotly)
n_smooth <- 1000

TT <- 3*pi
# parameter
t <- seq(0, TT, length.out = n_smooth)

# speed
speed <- sqrt(1 + cos(t)^2)

# arc-length function
s <- pracma::cumtrapz(t, speed)
# s <- cumsum(c(0, diff(t) * (head(speed,-1) + tail(speed,-1))/2))

L <- max(s)

half_L <- L / 2
half_TT <- TT / 2
dist_to_move <- abs(half_L - half_TT)

y_shift <- 4
# curve alpha(t)
x <- t + dist_to_move
y <- sin(t) + y_shift
z <- rep(0,length(t))

curve_smooth <- data.frame(x = x, y = y, z = z)


n_map <- 25
# points where we draw connectors
idx <- seq(1, length(t), length.out = n_map)


curve_map <- data.frame(x = x[idx], y = y[idx], z = z[idx])
int_map <- data.frame(x = s[idx], y = rep(0, n_map), z = rep(0, n_map))



# Build mapping lines
rows <- lapply(1:n_map, function(i) {
  list(int_map[i, ], curve_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result <- do.call(rbind, unlist(rows, recursive = FALSE))

s_circ <- L
radius <- s_circ / (2*pi)
x_shift_for_circle <- radius + TT + dist_to_move

theta <- seq(from=-pi,to=pi,length.out = n_smooth)
circle_curve <- data.frame(x = radius*cos(theta) + x_shift_for_circle, 
                    y = radius*sin(theta) + y_shift, 
                    z = rep(0, length(theta)))


circle_map <- circle_curve[idx, ]
dist_to_move_circle <- abs(half_L - y_shift)
int_map_circle <- data.frame(x = rep(x_shift_for_circle +2*radius, n_map), y = s[idx]-dist_to_move_circle, z = rep(0, n_map))

# Build mapping lines for circle
rows <- lapply(1:n_map, function(i) {
  list(int_map_circle[i, ], circle_map[i, ], data.frame(x = NA, y = NA, z = NA))
})

result_for_circle <- do.call(rbind, unlist(rows, recursive = FALSE))

v1 <- curve_map[1, ]
v2 <- curve_map[n_map, ]
e1 <- curve_map[ceiling(n_map/2), ]
e2 <- circle_map[ceiling(n_map/2), ]
zero1 <- int_map[1, ]
le1 <- int_map[n_map, ]

zero2 <- int_map_circle[1, ]
le2 <- int_map_circle[n_map, ]

vertex <- rbind(v1, v2, zero1, zero2, le1, le2)

p <- plot_ly() |>
  # smooth sin curve
  add_trace(data = curve_smooth,
  x = ~x, y = ~y, z = ~z,
  type = "scatter3d",
  mode = "lines",
  line = list(width = 7, color = "darkred"),
    showlegend = FALSE
) |>
  # sin curve
  add_trace(data = curve_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  # smooth circle curve
  add_trace(data = circle_curve,
  x = ~x, y = ~y, z = ~z,
  type = "scatter3d",
  mode = "lines",
  line = list(width = 7, color = "darkred"),
    showlegend = FALSE
) |>  
  add_trace(data = circle_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  # interval [0,L]
add_trace(data = int_map,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "lines+markers",
  line = list(width = 7, color = "#0000C8"),
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  # interval for circle
  add_trace(data = int_map_circle,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "lines+markers",
  line = list(width = 7, color = "#0000C8"),
  marker = list(size = 3, color = "rgba(0,0,0,0)"),
    showlegend = FALSE
) |>
  add_trace(data = vertex,
  x = ~x,
  y = ~y,
  z = ~z,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 5, color = "black"),
    showlegend = FALSE
) |> add_trace(
    type = "cone",
    x = e1$x,
    y = e1$y,
    z = e1$z,
    u = 1,
    v = 0,
    w = 0,
    sizemode = "absolute",
    sizeref = 0.4,
    colorscale = list(c(0, 1), c("green", "green")),
    showscale = FALSE
  ) |> add_trace(
    type = "cone",
    x = e2$x,
    y = e2$y,
    z = e2$z,
    u = 0,
    v = 1,
    w = 0,
    sizemode = "absolute",
    sizeref = 0.4,
    colorscale = list(c(0, 1), c("green", "green")),
    showscale = FALSE
  )

pal <- colorRampPalette(c("royalblue","cyan","yellow","red"))(100)

pal <- colorRampPalette(c(
  "#0000C8",  # dark navy
  "#0074D9",  # royalblue
  "#7FDBFF",  # cyan
  "#2ECC40",  # green
  "#FFDC00",  # yellow
  "#FF851B",  # orange
  "#FF4136",  # red
  "darkred"
))(100)

gradient_line <- function(p0, p1, n = 40){

  t <- seq(0,1,length.out = n)

  x <- (1-t)*p0$x + t*p1$x
  y <- (1-t)*p0$y + t*p1$y
  z <- (1-t)*p0$z + t*p1$z

  data.frame(x=x,y=y,z=z,t=t)
}


dx <- int_map$x - curve_map$x
dy <- int_map$y - curve_map$y
dz <- int_map$z - curve_map$z

norm <- sqrt(dx^2 + dy^2 + dz^2)

u <- dx / norm
v <- dy / norm
w <- dz / norm

dxc <- int_map_circle$x - circle_map$x
dyc <- int_map_circle$y - circle_map$y
dzc <- int_map_circle$z - circle_map$z

normc <- sqrt(dxc^2 + dyc^2 + dzc^2)

uc <- dxc / normc
vc <- dyc / normc
wc <- dzc / normc

p <- p |>
  add_trace(
    type = "cone",
    x = int_map$x,
    y = int_map$y,
    z = int_map$z,
    u = u,
    v = v,
    w = w,
    sizemode = "absolute",
    sizeref = 0.7,
    anchor = "tip",
    colorscale = list(c(0, "#0000C8"), c(1, "#0000C8")),
    showscale = FALSE
  ) |> add_trace(
    type = "cone",
    x = int_map_circle$x,
    y = int_map_circle$y,
    z = int_map_circle$z,
    u = uc,
    v = vc,
    w = wc,
    sizemode = "absolute",
    sizeref = 0.4,
    anchor = "tip",
    colorscale = list(c(0, "#0000C8"), c(1, "#0000C8")),
    showscale = FALSE
  )

for(i in 1:n_map){

  g <- gradient_line(int_map[i,], curve_map[i,])

  for(j in 1:(nrow(g)-1)){

    seg <- g[j:(j+1),]

    col <- pal[ round(seg$t[1]*(length(pal)-1))+1 ]

    p <- p |> add_trace(
      data = seg,
      x = ~x, y = ~y, z = ~z,
      type = "scatter3d",
      mode = "lines",
      line = list(color = col, width = 1),
      showlegend = FALSE
    )
  }
}

for(i in 1:n_map){

  g <- gradient_line(int_map_circle[i,], circle_map[i,])

  for(j in 1:(nrow(g)-1)){

    seg <- g[j:(j+1),]

    col <- pal[ round(seg$t[1]*(length(pal)-1))+1 ]

    p <- p |> add_trace(
      data = seg,
      x = ~x, y = ~y, z = ~z,
      type = "scatter3d",
      mode = "lines",
      line = list(color = col, width = 1),
      showlegend = FALSE
    )
  }
}



p4 <- p |>
  config(mathjax = 'cdn') |> 
  layout(p,
         font = list(family = "Palatino"),
            margin = list(l = 0, r = 0, b = 0, t = 0),
            scene = list(xaxis = list(title = list(text = "x", font = list(color = colaxnn)),  tickfont = list(color = colaxnn),  range = c(0, x_shift_for_circle +2*radius)*1.01),
              yaxis = list(title = list(text = "y", font = list(color = colaxnn)),  tickfont = list(color = colaxnn), range = range(int_map_circle$y)),
              zaxis = list(title = list(text = "z", font = list(color = colaxnn)),  tickfont = list(color = colaxnn), range = c(0, 0.2)),
    aspectratio = list(x = x_shift_for_circle +2*radius, y = L, z = 4),
              camera = list(eye = list(x = 0, y = -L*1.5, z = L*1.5),
                            center = list(x = 0, y = 0, z = 0)),
    annotations = list(
      list(
               x = zero1$x, y = zero1$y, z = zero1$z,
               text = TeX("0"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
      list(
               x = zero2$x, y = zero2$y, z = zero2$z,
               text = TeX("0"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
      list(
               x = le1$x, y = le1$y, z = le1$z,
               text = TeX("\\ell_{e_1}"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
      list(
               x = le2$x, y = le2$y, z = le2$z,
               text = TeX("\\ell_{e_2}"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
                list(
               x = v1$x, y = v1$y, z = v1$z,
               text = TeX("v_1"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = v2$x, y = v2$y, z = v2$z,
               text = TeX("v_2"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = e1$x, y = e1$y, z = e1$z,
               text = TeX("e_1"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1),
               list(
               x = e2$x, y = e2$y, z = e2$z,
               text = TeX("e_2"),
               textangle = 0, ax = 0, ay = -35,
               font = list(color = "black", size = gfsize),
               arrowcolor = "gray", arrowsize = 1, arrowwidth = 0.5, arrowhead = 1))
  )
)

save(p4, file = here::here("graphs6p4.Rdata"))
```


```{r, eval =TRUE, fig.height = 7, out.width = "100%"}
load(here::here("graphs6p4.Rdata"))
p4
```

